[build]
target = "index.html"
dist = "dist"

[build.subresource_integrity]
enabled = true

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["-y", "tailwindcss@3", "-i", "./input.css", "-o", "./tailwind.css"]
