[build]
target = "index.html"
dist = "dist"

[build.subresource_integrity]
enabled = true


[[hooks]]
stage = "pre_build"
command = "./node_modules/.bin/tailwindcss"
command_arguments = ["-i", "./input.css", "-o", "./tailwind.css"]